In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4])

In [5]:
print(arr[1])

2


In [6]:
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [9]:
print(arr2[0,3])

4


In [20]:
arr_3 = np.array([
    [[1,2,3,4,5],
     [6,7,8,9,10]],
    [[11,12,13,14,15],
     [16,17,18,29,20]]
])

In [21]:
print(arr_3.shape)

(2, 2, 5)


In [17]:
arr_3d = np.array([
    [[1],[2]], # block 0
    [[3],[4]], # block 1
    [[5],[6]]  # block 2
])

In [18]:
print(arr_3d.shape)

(3, 2, 1)


In [19]:
print(arr_3d)

[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]


In [23]:
arr_sh= np.arange(24).reshape(2,3,4)

In [24]:
print(arr_sh.shape)

(2, 3, 4)


In [25]:
print(arr_sh)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [26]:
print(arr_sh[1,1,3])

19


In [28]:
arr_sl = np.array([1,2,3,4,5,6,7])

In [33]:
print(arr_sl [:4])

[1 2 3 4]


In [34]:
print(arr_sl.dtype)

int32


In [36]:
arr_fl=np.array([1.4,2.3, 4.1])

In [37]:
print(arr_fl.dtype)

float64


In [38]:
arr_int_con = arr_fl.astype(int)

In [39]:
print(arr_int_con.dtype)

int32


In [40]:
print(arr_int_con)

[1 2 4]


In [41]:
arr_int = np.array([1,2,3,4,5,6,7])

In [44]:
arr_int_flo = arr_int.astype(float)

In [45]:
print(arr_int_flo)

[1. 2. 3. 4. 5. 6. 7.]


In [46]:
arr_b = np.array([1,0,1,1])

In [47]:
arr_b_conversion = arr_b.astype(bool)

In [48]:
print(arr_b_conversion)

[ True False  True  True]


In [51]:
arr_st = np.array(['True','False','False'])

In [52]:
print(arr_st.dtype)

<U5


In [72]:
arr_1d = np.array([1,2,3,4,5,6])

In [73]:
arr_1d_2d = arr_1d.reshape(3,2)

In [74]:
print(arr_1d_2d )

[[1 2]
 [3 4]
 [5 6]]


In [79]:
arr_1d_3d = arr_1d.reshape(3,2,1)

In [80]:
print(arr_1d_3d)

[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]


In [81]:
arr5 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [89]:
arr5_3d = arr5.reshape(5,2,1)

In [90]:
print(arr5_3d )

[[[ 1]
  [ 2]]

 [[ 3]
  [ 4]]

 [[ 5]
  [ 6]]

 [[ 7]
  [ 8]]

 [[ 9]
  [10]]]


In [17]:
a = np.array([[1],[2],[3]])         # has shape (3,1)

In [18]:
b = np.array([[4,5], [6,7], [8,9]]) # has shape (3,2)

In [21]:
c = a + b                    # will have shape (3,2)

In [22]:
print(c)

[[ 5  6]
 [ 8  9]
 [11 12]]
