In [1]:
import numpy as np

In [25]:
d_1 = np.array([
    [
     [11, 12, 13], 
     [14, 15, 16]
    ], 
    [
     [17, 18, 19], 
     [10, 11, 12]
    ],
    [
     [30, 31, 32], 
     [40, 41, 42]
    ],
    [
     [50, 51, 52], 
     [60, 61, 62]
    ]
    ])

In [ ]:
# [14, 15, 16], [17, 18, 19], [40, 41, 42], [60, 61, 62]

In [26]:
print(d_1[0,1,:],d_1[1,0,:],d_1[2,1,:],d_1[3,1,:])

[14 15 16] [17 18 19] [40 41 42] [60 61 62]


In [27]:
print("slicing_5 element of the table:", (d_1[0:4, 0]))

slicing_5 element of the table: [[11 12 13]
 [17 18 19]
 [30 31 32]
 [50 51 52]]


In [23]:
print("slicing_5 element of the table:", (d_1[0:3, 1]))

slicing_5 element of the table: [[14 15 16]
 [10 11 12]
 [40 41 42]]


In [38]:
arr = np.random.randint(1,11, size=(2,3,1))

In [39]:
print(arr)

[[[4]
  [6]
  [3]]

 [[6]
  [9]
  [5]]]


In [40]:
flat = arr.flatten()

In [41]:
print(flat)

[4 6 3 6 9 5]


In [43]:
print(flat.reshape(2,3)) # 2D

[[4 6 3]
 [6 9 5]]


In [44]:
print(flat.reshape(3,2,1)) # 3D

[[[4]
  [6]]

 [[3]
  [6]]

 [[9]
  [5]]]


In [52]:
arr1 = np.array([1,2,3,4])

In [53]:
arr2 = np.array([5,6,7,8])

In [60]:
arr_sum = np.divide(arr1,arr2)

In [61]:
print(arr_sum)

[0.2        0.33333333 0.42857143 0.5       ]


In [62]:
arr3 = np.array([-1,-2,-3,-4])

In [65]:
print(np.absolute(arr3))

[1 2 3 4]


In [69]:
arr_t = np.array([-1.22, -2.94])

In [70]:
print(np.trunc(arr_t))

[-1. -2.]


In [71]:
print(np.fix(arr_t))

[-1. -2.]


In [76]:
print(np.around(3.568, 2))

3.57


In [81]:
print(np.floor([-3.15,-2.15]))

[-4. -3.]
