# ●	Class 1: Descriptive statistics – mean, median, variance, standard deviation

## VECTORS - Representing of Data
- A Vector is an ordered list of numbers.
- It represents data points, weights of features.

x = [1,2,3] 

in ML each vectors ofter represents:
- A Feature vector(input)
- A Weighted vector(model parameters)

## MATRICES - Data Collections 
- A Matrix is a collection of vectors(rows or columns)

## DOT PRODUCT - Measuring Alignment
- The Dot product between two vectors measures similarity or alignment.

a.b = a1b1 + a2b2+....+anbn

[1,2,3].[4,5,6] = 1*4 + 2*5 + 3* 6 = 32 

## NORMS - Length or Magnitude 
- The norm of a vector = its length.

1. L2 Norm(Euclidean)
2. L1 Norm(Manhattan)
  

## Vectors Example

- Let's say you have a student's data:

1. Study hous = 2
2. IQ(scaled) = 3
3. Experiances = 5

vector x = [2,3,5]

In [19]:
import numpy as np
x = np.array([2,3,5])
print("Vector x:", x)
print("Shape:", x.shape) # 1D 

Vector x: [2 3 5]
Shape: (3,)


In [20]:
# [2,3,5], [4,5,6]

In [21]:
x = np.array([[2,3,5],[4,5,6]])
print("Vector x:", x)
print("Shape:", x.shape)  # 2D

Vector x: [[2 3 5]
 [4 5 6]]
Shape: (2, 3)


In [22]:
# Dot product - How similar or Aligned two vectors are
a = np.array([2,3,5])
b = np.array([4,5,6])
dot_product = np.dot(a,b)
print("Dot Product:", dot_product)

Dot Product: 53


# ML Meaning
- in Linear Regression:
  y = w.x + b

w = weights(model parameters)
x = input vector 
b = bias

In [23]:
w = np.array([1.5, 0.5, 2.0])   # study hour/features
x = np.array([20, 3, 50])   # IQ/weights
b = 1.0  
y = np.dot(w,x) + b
print("Predicted value:", y)

Predicted value: 132.5


In [24]:
# Norms
x = np.array([3,4])
l2_norm = np.linalg.norm(x)   # Eclidean: root(x1 squar + x2 square) 
l1_norm = np.linalg.norm(x,1)  # Manhattan : x1+x2
print(l2_norm)
print(l1_norm)

5.0
7.0


# House Price Prediction(Regression)
## Problem: Predict the price of a house bases on features like:
- Area(sq ft)
- Bedrooms
- Bathrooms
- Location Score

In [25]:
x = np.array([2000, 3, 2, 8])  # house features
w = np.array([50, 10, 5, 20])  # model wights 
b = 100                        # bias/base price
predcited_price = np.dot(w,x)+b
print("Predecited Price:",predcited_price)

Predecited Price: 100300


# ●	Class 2: Matrix operations in NumPy (inverses, eigenvalues)

In [26]:
A = np.array([[1,2],[3,4]])
print(A.T)

[[1 3]
 [2 4]]


In [29]:
# inverse
A = np.array([[1,2],[3,4]])
A_inv = np.linalg.inv(A)
print(A_inv)
print(np.dot(A, A_inv))  # should be identity

[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [31]:
# eigenvalues
eigvals, eigvecs = np.linalg.eig(A)
print("eigvals:", eigvals)
print("eigvecs:", eigvecs)

eigvals: [-0.37228132  5.37228132]
eigvecs: [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


# ●	Class 3: Derivatives, gradient descent, partial derivatives

In [32]:
# DERIVATIVES  - Rate of Change 

In [33]:
pip install sympy

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/6.3 MB ? eta -:--:--
   --- ------------------------------------ 0.5/6.3 MB 5.6 MB/s eta 0:00:02
   --------- ------------------------------ 1.6/6.3 MB 5.6 MB/s eta 0:00:01
   ------------------- -------------------- 3.1/6.3 MB 6.1 MB/s eta 0:00:01
   ------------------------ --------------- 3.9/6.3 MB 5.6 MB/s eta 0:00:01
   ------------------------------- -------- 5.0/6.3 MB 5.3 MB/s eta 0:00:01
   ------------------------------------ --- 5.8/6.3 MB 5.1 MB/s eta 0:00:01
   ---------------------------------------- 6.3/6.3 MB 4.8 MB/s  0:00:01
   ---------------------------------------- 0.0/536.2 kB ? eta -:--:--
   ---------------------------------------- 536.2/536.2 kB 17.1 MB/s  0:00:00

   ---------------------------------------- 0/2 [mpmath]
   ---------------------------------------- 0/2 [mpmath]
   ---------------------------------------- 0/2 [mpmath]
   

In [4]:
# Derivatives
import sympy as sp
x = sp.symbols('x')
f = x**2 
df = sp.diff(f,x)
print("Derivatives",df)
print("Value at x=3:", df.subs(x,3)) # how much to adjust parameters to reduce error. 

Derivatives 2*x
Value at x=3: 6


In [7]:
# Partial Derivatives
x, y = sp.symbols('x y')
f = x**2 + y**2
df_dx = sp.diff(f,x)
df_dy = sp.diff(f,y)
print("df/dx: ",df_dx)
print("df/dy: ", df_dy)

df/dx:  2*x
df/dy:  2*y
